### PR TITLE
chore: removed namespace env refs from examples

### PR DESCRIPTION
**Pull request by chipspeak**

### CODE REVIEW

**Comment by jsztuka** [comment]
Behavior has been tested on a local environment where the functionality has been confirmed.
Thanks for the first contribution, keep up the good work!

**Comment by jsztuka** [comment]
I suggest updating the task apiversion from **apiVersion: tekton.dev/v1beta1** to **apiVersion: tekton.dev/v1**.
Otherwise looks good!

**Comment by hongweiliu17** [comment]
> I suggest updating the task apiversion from **apiVersion: tekton.dev/v1beta1** to **apiVersion: tekton.dev/v1**. Otherwise looks good!

+1 for updating to `v1` in https://github.com/konflux-ci/integration-examples/pull/30/files#diff-5f32c6daae52f17372574a853abf75225e63505c3d6400e360d37a366dde4864R1. Others look good.

**Review by dirgim — APPROVED** [review]
LGTM

**Review by jsztuka — APPROVED** [review]
LGTM

**Pull request merged**
