### PR TITLE
fix(RHTAPBUGS-823): add retries for test_app_endpoint

### PR DESCRIPTION
**Pull request by dirgim**
* Add a retry loop with a 5-minute timeout for checking the endpoint content and making the decision if the test passed

### CODE REVIEW

**Comment by jinqi7** [comment]
LGTM

**Review by jinqi7 — APPROVED** [review]

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Comment by dheerajodha** [comment]
@dirgim I encountered this bug intermittently, so just to confirm, were you able to constantly see a successful Snapshot testing with this patch?

**Comment by dirgim** [comment]
> @dirgim I encountered this bug intermittently, so just to confirm, were you able to constantly see a successful Snapshot testing with this patch?

Yes, I was able to reliably replicate the bug by running 5-7 integration pipelines at the same time.
After applying the changes from this PR, all pipelines managed to pass after ~15-40 seconds by retrying 5-10 times, e.g.:

image

**Review by dheerajodha — APPROVED** [review]
LGTM!

**Review by MartinBasti — APPROVED** [review]

**Pull request merged**
